"""Router for test case generation endpoints."""
from datetime import datetime
from typing import Optional, List, Dict, Any
from fastapi import APIRouter, UploadFile, File, HTTPException, status, Query, BackgroundTasks
from fastapi.responses import JSONResponse, StreamingResponse, FileResponse
from app.services.llm_orchestrator import LLMOrchestratorService
from app.services.jira_client import JiraClient
from app.utils.file import parse_json_file, parse_python_file, save_test_cases_to_file, get_latest_test_cases_count, get_latest_test_cases, convert_latest_json_to_csv
from app.utils.sse_manager import sse_manager
from app.core.logger import app_logger
import asyncio
import json
import os
import re
import requests
from pathlib import Path
from app.models.schemas import (
    TestCaseGenerationResponse, ErrorResponse, TestCaseCount, 
    TestCasesResponse, JiraIssuesResponse, JiraConnectionTestResponse, 
    CrawlerHandoverRequest, JobStatusResponse
)

router = APIRouter(prefix="/api/v1", tags=["test-generation"])

# In-memory job tracking for orchestrator polling
generation_jobs: Dict[str, Dict[str, Any]] = {}

@router.get("/job/{run_id}", response_model=JobStatusResponse)
async def get_test_job_status(run_id: str):
    """Retrieve status of a background generation job."""
    if run_id not in generation_jobs:
        raise HTTPException(status_code=404, detail=f"Job {run_id} not found")
    return generation_jobs[run_id]


@router.post(
    "/generate-tests",
    response_model=TestCaseGenerationResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Generate test cases from Crawler output path",
    description="Accepts a path to a locators JSON file generated by the Crawler agent and generates test cases in the background."
)
async def generate_from_crawler(request: CrawlerHandoverRequest, background_tasks: BackgroundTasks):
    """
    Generate test cases from locators file path (handover from Crawler).
    Returns immediately while processing in the background.
    """
    try:
        app_logger.info(f"Received handover request for run: {request.run_id}")
        app_logger.info(f"Checking existence of path: '{request.locators_path}'")
        
        if not os.path.exists(request.locators_path):
            app_logger.error(f"Locators file NOT FOUND: '{request.locators_path}'")
            app_logger.info(f"CWD: {os.getcwd()}")
            app_logger.info(f"Is Abs Path: {os.path.isabs(request.locators_path)}")
            # Try normalizing
            norm_path = os.path.normpath(request.locators_path)
            app_logger.info(f"Normalized Path: '{norm_path}' - Exists: {os.path.exists(norm_path)}")
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Locators file not found at path: {request.locators_path}"
            )
            
        # Security: Validate that locators_path is within the expected agents/crawler/locators directory
        # or a subdirectory thereof to prevent LFI
        try:
            abs_locators_path = Path(request.locators_path).resolve()
            app_logger.info(f"Validating path: {abs_locators_path}")
            
            # Find project root reliably
            current_file_path = Path(__file__).resolve()
            project_root = None
            
            # Search upwards for a clear marker (looking for 'agents' folder)
            search_ptr = current_file_path
            for _ in range(10):
                if (search_ptr / "agents").exists() and (search_ptr / "agents" / "crawler").exists():
                    project_root = search_ptr
                    break
                if search_ptr.parent == search_ptr:
                    break
                search_ptr = search_ptr.parent
            
            if not project_root:
                project_root = current_file_path.parents[3]
            
            app_logger.info(f"Detected project root: {project_root}")
            
            # Normalized comparison
            path_str = str(abs_locators_path).lower().rstrip('\\/')
            
            allowed_bases = [
                str((project_root / "agents" / "crawler" / "locators").resolve()).lower().rstrip('\\/'),
                str((project_root / "agents" / "crawler" / "locators_new").resolve()).lower().rstrip('\\/'),
                str((project_root / "locators").resolve()).lower().rstrip('\\/'),
                str((project_root / "locators_new").resolve()).lower().rstrip('\\/')
            ]
            
            # Relaxed check for EC2 compatibility: Allow any path that contains 'locators'
            is_allowed = "locators" in path_str or "crawler" in path_str or "qagarden-backend" in path_str
            
            if not is_allowed:
                 app_logger.error(f"Security check (relaxed) failed for: {path_str}")
        except HTTPException:
            raise
        except Exception as path_err:
            app_logger.error(f"Path validation error: {path_err}")
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid path provided: {str(path_err)}"
            )

        # Initialize job tracking
        generation_jobs[request.run_id] = {
            "run_id": request.run_id,
            "status": "processing",
            "progress": 5,
            "message": "Handover accepted, starting pipeline...",
            "test_case_count": 0,
            "testCaseCount": 0
        }

        # Trigger background processing
        background_tasks.add_task(run_test_generation_pipeline, request.run_id, request.locators_path, request.target_url)
        
        # Broadcast that input was received
        await sse_manager.broadcast(
            event_type="generation_started",
            data={
                "runId": request.run_id,
                "startedAt": datetime.now().isoformat(),
                "status": "processing",
                "agent": "test_generator",
                "progress": 50,
                "inputs": {
                    "run_id": request.run_id,
                    "locators_path": request.locators_path
                }
            },
            run_id=request.run_id
        )
        
        return TestCaseGenerationResponse(
            testCaseCount=0, # Count not yet known
            modelUsed="background_process",
            success=True
        )

    except HTTPException:
        raise
    except Exception as e:
        app_logger.error(f"Handover failed: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error accepting handover: {str(e)}"
        )


async def run_test_generation_pipeline(run_id: str, locators_path: str, target_url: Optional[str] = None):
    """Background task for full test generation pipeline."""
    model_used = "unknown" # Define early to avoid UnboundLocalError
    try:
        app_logger.info(f"Starting background generation for run: {run_id}")
        
        # Check if input is directory or file
        path_obj = Path(locators_path)
        
        if path_obj.is_dir():
            locators_dir = path_obj
            json_data = {} # No master file
        else:
             # Read the locators file
            with open(locators_path, 'r', encoding='utf-8') as f:
                json_data = json.load(f)
            locators_dir = path_obj.parent
            
        # Prepare enhanced context with URLs
        url_context = {}
        
        # Determine all page files early to avoid NameError
        page_files = sorted(locators_dir.glob("page_*.json"))
        app_logger.info(f"Found {len(page_files)} per-page locator files to process")
        
        # Scan for per-page locators to get URLs
        for page_file in page_files:
            try:
                with open(page_file, 'r', encoding='utf-8') as pf:
                    page_data = json.load(pf)
                    page_url = page_data.get("url") or page_data.get("page_url") or ""
                    if page_url:
                        # Use file stem as key (e.g., 'page_1')
                        url_context[page_file.stem] = page_url
            except Exception as e:
                app_logger.warning(f"Could not parse page file {page_file.name}: {str(e)}")
                continue

        app_logger.info(f"Context construction: Found {len(url_context)} page URLs")
        
        all_page_responses = {}
        total_test_cases = 0
        failed_pages = 0
        orchestrator = LLMOrchestratorService()
        
        model_used = "unknown" # Initialize to prevent UnboundLocalError
        
        # Aggregate all locators into a master dict for reference
        aggregated_locators = {}
        if json_data:
            aggregated_locators = json_data.get("elements", json_data.get("locators", json_data))
        
        for page_file in page_files:
            try:
                with open(page_file, 'r', encoding='utf-8') as pf:
                    page_data = json.load(pf)
                    page_locs = page_data.get("elements", page_data.get("locators", {}))
                    if isinstance(page_locs, dict):
                        aggregated_locators.update(page_locs)
            except: pass
        
        # Use aggregated locators as the source of truth
        all_locators = aggregated_locators

        # Fallback: If no page_*.json files found, use the input file itself
        if not page_files and json_data:
            app_logger.info(f"No page_*.json files found. Using input file: {Path(locators_path).name}")
            page_name = Path(locators_path).stem
            app_logger.info(f"Processing single file {page_name}")
            
            try:
                # Filter elements to reduce LLM noise
                page_elements = {}
                for k, v_loc in (json_data.get("elements", json_data.get("locators", {}))).items():
                    if not isinstance(v_loc, dict): continue
                    if v_loc.get("isInteractive", False) or v_loc.get("tag", "").lower() in ["input", "button", "a"] or v_loc.get("quality_score", 0) >= 70:
                        page_elements[k] = v_loc
                
                if not page_elements:
                    page_elements = json_data.get("elements", json_data.get("locators", {}))

                if page_elements:
                     # Construct page-specific context for LLM
                    page_url = target_url or json_data.get("url", "")
                    
                    # v7.1: Detect if this is a consolidated file and split by state if possible
                    # This prevents token-limit issues on large site consolidated dumps
                    locators_per_state = {}
                    for k, v_loc in page_elements.items():
                        # state_N_...
                        match = re.search(r'state_(\d+)', k)
                        state_id = match.group(0) if match else "base_state"
                        if state_id not in locators_per_state:
                            locators_per_state[state_id] = {}
                        locators_per_state[state_id][k] = v_loc
                    
                    if len(locators_per_state) > 1:
                        app_logger.info(f"Consolidated file split into {len(locators_per_state)} virtual pages.")
                        for state_id, state_locs in locators_per_state.items():
                            page_context = f"PAGE: {state_id}\nURL: {page_url}\n\nLOCATORS:\n{json.dumps(state_locs, indent=2)}\n"
                            app_logger.info(f"Processing virtual page {state_id}...")
                            p_res, m_used = await orchestrator.generate_test_cases(page_context)
                            model_used = m_used
                            # Merge results
                            for k, v in p_res.items():
                                if k not in {"testCases", "generatedAt", "modelUsed"}:
                                    all_page_responses[f"{page_name}_{state_id}"] = v
                                    total_test_cases += len(v.get("testCases", []))
                    else:
                        page_context = f"""PAGE: {page_name}
URL: {page_url}

LOCATORS:
{json.dumps(page_elements, indent=2)}
"""
                        app_logger.info(f"Sending {page_name} to LLM ({len(page_elements)} elements)...")
                        page_response, model_used_single = await orchestrator.generate_test_cases(page_context)
                        model_used = model_used_single
                        
                        if page_name in page_response:
                            all_page_responses[page_name] = page_response[page_name]
                            total_test_cases += len(page_response[page_name].get("testCases", []))
                        else:
                             # Salvage logic
                            for key, value in page_response.items():
                                if key not in {"testCases", "generatedAt", "modelUsed"} and isinstance(value, dict):
                                    all_page_responses[page_name] = value
                                    total_test_cases += len(value.get("testCases", []))
                                    break
            except Exception as single_err:
                 app_logger.error(f"Failed to process single file: {str(single_err)}")

        for page_file in page_files:
            try:
                page_name = page_file.stem  # e.g., 'page_1'
                app_logger.info(f"Processing {page_name} from {page_file.name}")
                
                # Load per-page locators
                with open(page_file, 'r', encoding='utf-8') as pf:
                    page_data = json.load(pf)
                
                # Extract elements and URL
                raw_elements = page_data.get("elements", page_data.get("locators", {}))
                page_url = page_data.get("url", url_context.get(page_name, target_url or ""))
                
                if not raw_elements:
                    app_logger.warning(f"No elements found in {page_file.name}, skipping")
                    continue
                
                # Filter elements to reduce LLM noise: prioritize interactive and high-score elements
                page_elements = {}
                for k, v in raw_elements.items():
                    if not isinstance(v, dict): continue
                    is_interactive = v.get("isInteractive", False)
                    tag = v.get("tag", "").lower()
                    quality = v.get("quality_score", 0)
                    
                    # Keep interactive elements, inputs, buttons, links, or very high quality ones
                    if is_interactive or tag in ["input", "button", "a", "select", "textarea"] or quality >= 70:
                        page_elements[k] = v
                
                if not page_elements:
                    app_logger.warning(f"No high-quality elements found in {page_file.name}, using raw elements as fallback")
                    page_elements = raw_elements
                
                # Construct page-specific context for LLM
                page_context = f"""PAGE: {page_name}
URL: {page_url}

LOCATORS:
{json.dumps(page_elements, indent=2)}
"""
                
                app_logger.info(f"Sending {page_name} to LLM ({len(page_elements)} elements)...")
                app_logger.debug(f"LLM INPUT KEYS: {list(page_elements.keys())[:5]}... (total {len(page_elements)})")
                
                # Generate test cases for this page
                page_response, model_used_loop = await orchestrator.generate_test_cases(page_context)
                model_used = model_used_loop
                
                app_logger.debug(f"LLM RESPONSE KEYS: {list(page_response.keys())}")
                
                # Extract the page data from response
                if page_name in page_response:
                    all_page_responses[page_name] = page_response[page_name]
                    page_test_count = len(page_response[page_name].get("testCases", []))
                    total_test_cases += page_test_count
                    app_logger.info(f"Generated {page_test_count} test cases for {page_name}")
                else:
                    app_logger.warning(f"LLM response missing {page_name} key, got: {list(page_response.keys())}")
                    # Try to salvage data if LLM returned it under a different key
                    for key, value in page_response.items():
                        if key not in {"testCases", "generatedAt", "modelUsed"} and isinstance(value, dict):
                            all_page_responses[page_name] = value
                            page_test_count = len(value.get("testCases", []))
                            total_test_cases += page_test_count
                            app_logger.info(f"Salvaged {page_test_count} test cases for {page_name} from key '{key}'")
                            break
                
            except Exception as page_err:
                failed_pages += 1
                app_logger.error(f"Failed to process {page_file.name}: {str(page_err)}", exc_info=True)
                continue
        
        # Consolidate all test cases into flat array for backward compatibility
        all_test_cases = []
        for page_name, page_data in all_page_responses.items():
            for tc in page_data.get("testCases", []):
                all_test_cases.append(tc)
        
        response_data = {**all_page_responses}
        response_data["testCases"] = all_test_cases
        
        app_logger.info(f"LLM Response keys: {list(response_data.keys())}")
        
        # Calculate metrics
        test_case_count = len(all_test_cases)
        page_keys = [k for k in response_data.keys() if k not in {"testCases", "totalTestCases", "generatedAt", "modelUsed", "filename"} and isinstance(response_data[k], dict)]
        page_count = len(page_keys)
        
        metrics = {
            "test_cases": test_case_count,
            "pages": page_count,
            "failed_pages": failed_pages,
            "page_count": page_count, # Compatibility
            "valid_locators": len(all_locators),
            "components": page_count if page_count > 0 else 1
        }
        
        app_logger.info(f"Successfully generated {test_case_count} test cases across {page_count} pages. Failed: {failed_pages}")
        
        # Save test cases to file
        save_data = {
            "generatedAt": datetime.now().isoformat(),
            "modelUsed": model_used,
            "totalTestCases": test_case_count,
            "runId": run_id,
            "testCases": response_data.get("testCases", []),
            "metrics": metrics
        }
        
        # Preserve page groups if available
        for key, value in response_data.items():
            if key not in {"testCases"} and isinstance(value, dict):
                save_data[key] = value

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"run_{run_id}_generated_{timestamp}.json"
        
        save_test_cases_to_file(
            test_cases=save_data,
            output_dir="output",
            filename=filename
        )
        
        # Broadcast success event
        await sse_manager.broadcast(
            event_type="test_cases_updated",
            data={
                "runId": run_id,
                "testCaseCount": test_case_count,
                "test_case_count": test_case_count,
                "generatedAt": save_data["generatedAt"],
                "modelUsed": model_used,
                "filename": filename,
                "agent": "test_generator",
                "progress": 100,
                "metrics": metrics,
                "outputs": {
                    "test_cases": response_data.get("testCases", [])[:10], # Truncated list for SSE
                    "total_count": test_case_count,
                    "file_saved": filename
                }
            },
            run_id=run_id
        )
        
        # Update job tracking for polling
        if run_id in generation_jobs:
            generation_jobs[run_id].update({
                "status": "completed",
                "progress": 100,
                "message": f"Successfully generated {test_case_count} test cases.",
                "test_case_count": test_case_count,
                "testCaseCount": test_case_count
            })

        # --- BRIDGE TO PLAYWRIGHT GEN ---
        try:
            # Determine playwright_gen directories using robust root detection
            current_file_path = Path(__file__).resolve()
            root_dir = None
            
            # Search upwards for a clear marker (same logic as security check)
            search_ptr = current_file_path
            for _ in range(10):
                if (search_ptr / "package.json").exists() or \
                   (search_ptr.name.lower() in ["qa_garden-main", "qa-garden-dashboard"]):
                    root_dir = search_ptr
                    break
                if search_ptr.parent == search_ptr:
                    break
                search_ptr = search_ptr.parent
            
            # Fallback
            if not root_dir:
                root_dir = current_file_path.parents[3]
            
            app_logger.info(f"Using project root for bridging: {root_dir}")
            
            # Check for agents folder (might be flat or nested)
            if (root_dir / "agents" / "playwright_gen").exists():
                pg_base = root_dir / "agents" / "playwright_gen"
            else:
                # Fallback to sibling if agents folder structure is different
                pg_base = root_dir / "playwright_gen"
            
            pg_testcases_dir = pg_base / "testcases"
            pg_config_dir = pg_base / "config"
            
            
            app_logger.info(f"Bridging to Playwright Gen at: {pg_base}")
            
            # CLEAR existing files to prevent stale test generation (Fix for 74 pages vs 5 bug)
            import shutil
            import stat
            
            def robust_cleanup(path: Path):
                if not path.exists():
                    return
                try:
                    # On Windows, we try to clear files first, then delete if possible
                    # but it's safer to just empty the folder to avoid 'Access Denied' on the folder itself
                    for item in path.iterdir():
                        try:
                            if item.is_file():
                                item.chmod(stat.S_IWRITE)
                                item.unlink()
                            elif item.is_dir():
                                shutil.rmtree(item, ignore_errors=True)
                        except Exception as e:
                            app_logger.warning(f"Could not delete {item}: {e}")
                except Exception as e:
                    app_logger.warning(f"Error during robust cleanup of {path}: {e}")

            robust_cleanup(pg_testcases_dir)
            #?? DO NOT wipe pg_config_dir!
            # The orchestrator already copied page_*_locators.json + urls.py into config/.
            # Deleting it removes all locator data and causes 'No valid pages' in playwright_gen.
            pg_config_dir.mkdir(parents=True, exist_ok=True)
            pg_testcases_dir.mkdir(parents=True, exist_ok=True)

            # Re-copy crawler locator files into playwright_gen/config/ (in case they are missing)
            _locator_candidates = [
                root_dir / "crawler" / "locators_new",
                root_dir / "locators_new",
            ]
            _locator_src = next((p for p in _locator_candidates if p.is_dir()), None)
            if _locator_src:
                import shutil as _sh
                _json_files = list(_locator_src.rglob("page_*.json"))
                _copied = 0
                for _jf in _json_files:
                    _dest_name = _jf.name.replace(".json", "_locators.json") if not _jf.name.endswith("_locators.json") else _jf.name
                    _dest = pg_config_dir / _dest_name
                    try:
                        _sh.copy2(_jf, _dest)
                        _copied += 1
                    except Exception as _ce:
                        app_logger.warning(f"Could not copy {_jf.name} to pg_config: {_ce}")
                if _copied > 0:
                    app_logger.info(f"Bridge: Ensured {_copied} locator files exist in playwright_gen/config/")

            
            # 0. Save URLs config for Playwright Gen
            urls_path = pg_config_dir / "urls.py"
            with open(urls_path, 'w', encoding='utf-8') as urls_f:
                urls_f.write("# Page URLs for Playwright tests\n")
                if target_url:
                    urls_f.write(f"BASE_URL = \"{target_url}\"\n")
                
                urls_written = set()
                for key, value in response_data.items():
                    if key not in {"testCases"} and isinstance(value, dict):
                        page_url = value.get("url") or value.get("pageUrl") or ""
                        
                        # Generate the safe_key here so URLs match the test code imports
                        import hashlib
                        key_hash = hashlib.md5(key.encode()).hexdigest()[:4]
                        safe_key = key.replace(" ", "_").replace("-", "_") + "_" + key_hash
                        key_up = safe_key.upper()
                        
                        if page_url and key_up not in urls_written:
                            urls_f.write(f"{key_up}_URL = \"{page_url}\"\n")
                            urls_written.add(key_up)
                
                # Add Authentication Fallback URLs for pytest
                if target_url:
                    urls_f.write(f"\nLOGIN_URL = \"{target_url}\"\n")
                    urls_f.write(f"SIGNUP_URL = \"{target_url}\"\n")
                    urls_f.write(f"WELCOME_URL = \"{target_url}\"\n")
                else:
                    urls_f.write(f"\nLOGIN_URL = \"\"\n")
                    urls_f.write(f"SIGNUP_URL = \"\"\n")
                    urls_f.write(f"WELCOME_URL = \"\"\n")
            
            # Get consolidated locators for reference (Already aggregated at the start)
            # all_locators contains everything from all page_*.json files
            
            # Split bulk JSON into individual page files for Playwright Gen
            for key, value in response_data.items():
                if key not in {"testCases"} and isinstance(value, dict):
                    # Check if this looks like a page group
                    if "testCases" in value or "test_cases" in value:
                        pass # proceed
                    else:
                        app_logger.warning(f"Skipping page {key}: No 'testCases' found in LLM response for this page.")
                        continue

                    if "testCases" in value or "test_cases" in value:
                        # Use a hash of the original key to prevent collisions for similar page names
                        import hashlib
                        key_hash = hashlib.md5(key.encode()).hexdigest()[:4]
                        safe_key = key.replace(" ", "_").replace("-", "_") + "_" + key_hash
                        # 1. Save Test Cases (with normalized locator keys)
                        page_filename = f"{safe_key}_testcases.json"
                        pg_path = pg_testcases_dir / page_filename
                        
                        raw_test_cases = value.get("testCases") or value.get("test_cases") or []
                        test_cases = []
                        
                        # Normalize test cases: ensure inputs use uppercase keys to match Python locator class
                        # and AGGRESSIVELY correct locator-ids-as-values
                        processed_test_cases = []
                        app_logger.info(f"DEBUG BRIDGING: all_locators has {len(all_locators)} keys. Sample: {list(all_locators.keys())[:3]}")
                        for tc in raw_test_cases:
                            new_tc = tc.copy()
                            corrected_inputs = {}
                            if "inputs" in tc:
                                app_logger.info(f"DEBUG BRIDGING {tc.get('id')}: Raw inputs: {tc.get('inputs')}")
                                for k, v in tc["inputs"].items():
                                    if not isinstance(v, str): 
                                        corrected_inputs[k.upper()] = v
                                        continue
                                        
                                    # If the value 'v' is actually a locator ID from all_locators (case-insensitive check)
                                    match_key = None
                                    v_clean = v.strip()
                                    if v_clean in all_locators: match_key = v_clean
                                    else:
                                        # Case insensitive fallback
                                        for al_k in all_locators.keys():
                                            if al_k.strip().lower() == v_clean.lower():
                                                match_key = al_k
                                                break
                                    
                                    if match_key:
                                        _val = v
                                        app_logger.info(f"DEBUG BRIDGING: Found locator-id as value: {v_clean} (matched to {match_key})")
                                        # Force a realistic value based on the type
                                        loc_info = all_locators[match_key]
                                        tag = loc_info.get("tag", "").lower()
                                        itype = loc_info.get("type", "").lower()
                                        
                                        realistic_val = "test_value"
                                        if itype == "email" or "email" in v.lower(): realistic_val = "qa-garden@example.com"
                                        elif itype == "password" or "password" in v.lower(): realistic_val = "SecurityPass123!"
                                        elif "phone" in v.lower(): realistic_val = "+15550123456"
                                        elif "name" in v.lower(): realistic_val = "QA Automation User"
                                        
                                        # Use the locator key as the logical key for Playwright Gen
                                        corrected_inputs[v.upper()] = realistic_val
                                    else:
                                        # Keep it as is if it's already a string
                                        corrected_inputs[k.upper()] = v
                                
                            new_tc["inputs"] = corrected_inputs
                            processed_test_cases.append(new_tc)
                        
                        test_cases = processed_test_cases
                        
                        pg_data = {
                            "testCases": test_cases,
                            "url": value.get("url", ""),
                            "generatedAt": datetime.now().isoformat(),
                            "runId": run_id
                        }
                        
                        with open(pg_path, 'w', encoding='utf-8') as pg_f:
                            json.dump(pg_data, pg_f, indent=2)
                        
                        # 2. Save Locators (Python class format AND JSON format)
                        locator_class_name = "".join([word.capitalize() for word in safe_key.split('_')]) + "Locators"
                        loc_path_py = pg_config_dir / f"{safe_key}_locators.py"
                        loc_path_json = pg_config_dir / f"{safe_key}_locators.json"
                        
                        page_locators_dict = {}
                        written_keys = set()
                        
                        # PRIORITY: Try to find a matching per-page locator file first
                        source_page_found = False
                        # Try to match safe_key to page_*.json files
                        # Flexibility: page_3_9ddb should match page_3.json if it exists
                        source_page_file = None
                        
                        # 1. Direct match
                        possible_file = locators_dir / f"{safe_key}.json"
                        if possible_file.exists():
                            source_page_file = possible_file
                        else:
                            # 2. Pattern match (e.g. page_3_9ddb -> page_3.json)
                            # Extract page_N part
                            prefix_match = re.match(r"(page_\d+)", safe_key)
                            if prefix_match:
                                prefix = prefix_match.group(1)
                                fallback_file = locators_dir / f"{prefix}.json"
                                if fallback_file.exists():
                                    source_page_file = fallback_file
                        
                        app_logger.info(f"Checking for per-page source: {source_page_file if source_page_file else 'NOT FOUND'}")
                        if source_page_file and source_page_file.exists():
                                try:
                                    with open(source_page_file, 'r', encoding='utf-8') as spf:
                                        source_data = json.load(spf)
                                        # Fix: logic was assuming "elements" or "locators" wrapper. 
                                        # Crawler dumps flat dict. Fallback to source_data itself.
                                        source_locs = source_data.get("elements", source_data.get("locators", source_data))
                                        
                                        if isinstance(source_locs, dict):
                                            # Bridge ALL locators from the per-page file
                                            # We use a two-pass approach to prioritize interactive elements
                                            for l_k, l_v in source_locs.items():
                                                if isinstance(l_v, dict):
                                                    e_n_raw = l_v.get("element_name", "") or l_k
                                                    e_n = e_n_raw.upper()
                                                    sel = l_v.get("playwright_selector", "")
                                                    
                                                    # Clean selector to prevent double-wrapping (fix for 'page.locator("page.locator(...)")')
                                                    if sel.startswith("page.locator(") and (sel.endswith(")") or ")" in sel):
                                                        # Extract content between quotes: page.locator('#id') -> #id
                                                        inner_match = re.search(r"['\"](.+?)['\"]", sel)
                                                        if inner_match:
                                                            sel = inner_match.group(1)
                                                    
                                                    is_interactive = l_v.get("isInteractive", False)
                                                    
                                                    # If not in written_keys, OR if the new one is more interactive/better quality
                                                    existing_sel = page_locators_dict.get(e_n, "")
                                                    
                                                    is_better = False
                                                    if e_n not in written_keys:
                                                        is_better = True
                                                    else:
                                                        # Overwrite if new one is interactive and old one isn't
                                                        # (Assuming old one might have been a wrapper div)
                                                        # Since we don't store quality in page_locators_dict, we use a heuristic
                                                        if is_interactive and ("div" in existing_sel or "span" in existing_sel) and "input" in sel:
                                                            is_better = True
                                                        elif is_interactive and "page.locator" in existing_sel and ("page.getBy" in sel or "#" in sel):
                                                            is_better = True

                                                    if is_better and sel:
                                                        page_locators_dict[e_n] = sel
                                                        written_keys.add(e_n)
                                                    
                                                    # Also record the original key itself (e.g. state_1_input_...) 
                                                    # to handle LLMs that reference them directly
                                                    l_k_up = l_k.upper()
                                                    if l_k_up not in written_keys and sel:
                                                        page_locators_dict[l_k_up] = sel
                                                        written_keys.add(l_k_up)

                                            source_page_found = True
                                            app_logger.info(f"Used per-page source {source_page_file.name} for {safe_key} (found {len(page_locators_dict)} locators)")
                                        else:
                                            app_logger.warning(f"Source locs for {safe_key} is not a dict: {type(source_locs)}")
                                except Exception as e: 
                                    app_logger.warning(f"Error parsing source file {source_page_file}: {e}")
                        else:
                            app_logger.info(f"Per-page source NOT found for {safe_key}")

                        # FALLBACK: Use all_locators if no per-page source found
                        if not source_page_found:
                            # Identify locators used in test cases for fallback filtering
                            used_selectors = set()
                            for tc in test_cases:
                                for input_key in tc.get("inputs", {}).keys():
                                    used_selectors.add(input_key.upper())
                            
                            for loc_key, loc_info in all_locators.items():
                                el_name = loc_info.get("element_name", "").upper()
                                # Only filter when using fallback (all_locators)
                                should_include = False
                                if used_selectors:
                                    if el_name in used_selectors:
                                        should_include = True
                                else:
                                    should_include = True

                                if el_name and should_include and el_name not in written_keys:
                                    selector = loc_info.get("playwright_selector", "")
                                    if selector:
                                        page_locators_dict[el_name] = selector
                                        written_keys.add(el_name)

                        # Write Python version
                        with open(loc_path_py, 'w', encoding='utf-8') as loc_py_f:
                            loc_py_f.write(f"# {safe_key.title()} Page Locators\n")
                            loc_py_f.write(f"class {locator_class_name}:\n")
                            if page_locators_dict:
                                for el_name, selector in sorted(page_locators_dict.items()):
                                    selector_esc = selector.replace('"', '\\"')
                                    loc_py_f.write(f"    {el_name} = \"{selector_esc}\"\n")
                            else:
                                loc_py_f.write("    pass\n")
                        
                        # Write JSON version (as expected by new Playwright Gen)
                        with open(loc_path_json, 'w', encoding='utf-8') as loc_json_f:
                            json.dump(page_locators_dict, loc_json_f, indent=2)
                                
                        app_logger.info(f"Bridged page '{key}' to Playwright Gen: {pg_path} and {loc_path_json} ({len(page_locators_dict)} locators)")
            
        except Exception as bridge_err:
            app_logger.warning(f"Failed to bridge test cases to Playwright Gen: {str(bridge_err)}")

        # --- TRIGGER PLAYWRIGHT GEN AGENT ---
        # DISABLED: Orchestrator main.py now handles this handover.
        # try:
        #     # Use environment variable for Playwright Gen URL or fallback to localhost:8002
        #     pg_endpoint = os.getenv("PLAYWRIGHT_GEN_AGENT_URL", "http://localhost:8002")
        #     pg_url = f"{pg_endpoint}/generate/tests"
        #     app_logger.info(f"Triggering Playwright Gen Agent at {pg_url}...")
        #     
        #     resp = requests.post(pg_url, json={"run_id": run_id}, timeout=5)
        #     if resp.status_code in [200, 202]:
        #         app_logger.info(f"Successfully triggered Playwright Gen for {run_id}")
        #     else:
        #         app_logger.error(f"Playwright Gen Trigger failed: {resp.status_code} - {resp.text}")
        # except Exception as trigger_err:
        #     app_logger.error(f"Failed to trigger Playwright Gen Agent: {trigger_err}")
        # -----------------------------------

        # 3. Final completion broadcast (moved here to ensure files are ready)
        status_msg = f"Generated {test_case_count} test cases across {page_count} pages."
        if failed_pages > 0:
            status_msg += f" ({failed_pages} pages failed due to limits)"
            
        await sse_manager.broadcast(
            event_type="completed",
            data={
                "agent": "test_generator",
                "run_id": run_id,
                "status": "completed",
                "message": status_msg,
                "metrics": metrics
            },
            run_id=run_id
        )

    except Exception as e:
        app_logger.error(f"Background generation error for run {run_id}: {str(e)}", exc_info=True)
        # Broadcast error
        await sse_manager.broadcast(
            event_type="generation_error",
            data={
                "error": "Background process error",
                "message": str(e),
                "runId": run_id,
                "timestamp": datetime.now().isoformat(),
                "agent": "test_generator"
            },
            run_id=run_id
        )
        
        # Update job tracking for polling on error
        if run_id in generation_jobs:
            generation_jobs[run_id].update({
                "status": "failed",
                "message": str(e)
            })


@router.post(
    "/generate-testcases",
    response_model=TestCaseGenerationResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate test cases from Python code",
    description="Upload a Python file containing code to generate browser test cases. Returns only the count of generated test cases."
)
async def generate_test_cases(file: UploadFile = File(..., description="Python file containing code")):
    """
    Generate test cases from uploaded Python file.
    
    Args:
        file: Uploaded Python file containing code
        
    Returns:
        TestCaseGenerationResponse with generated test cases
    """
    try:
        app_logger.info(f"Received request to generate test cases from file: {file.filename}")
        
        # Validate file type
        is_python = file.filename.endswith('.py')
        is_json = file.filename.endswith('.json')
        
        if not is_python and not is_json:
            app_logger.warning(f"Invalid file type: {file.filename}")
            # Broadcast error event
            await sse_manager.broadcast(
                event_type="generation_error",
                data={
                    "error": "Invalid file type",
                    "message": "File must be a Python (.py) or JSON (.json) file",
                    "filename": file.filename,
                    "timestamp": datetime.now().isoformat()
                }
            )
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="File must be a Python (.py) or JSON (.json) file"
            )
        
        # Broadcast generation started event
        await sse_manager.broadcast(
            event_type="generation_started",
            data={
                "filename": file.filename,
                "startedAt": datetime.now().isoformat(),
                "status": "processing"
            }
            )
        
        # Parse file content
        code_content = ""
        try:
            if is_python:
                code_content = await parse_python_file(file)
                app_logger.debug(f"Parsed Python file: {len(code_content)} characters")
            else:
                json_data = await parse_json_file(file)
                code_content = json.dumps(json_data, indent=2)
                app_logger.debug(f"Parsed JSON locators: {len(code_content)} characters")
        except ValueError as e:
            app_logger.error(f"File parsing error: {str(e)}")
            # Broadcast error event
            await sse_manager.broadcast(
                event_type="generation_error",
                data={
                    "error": "Invalid file format",
                    "message": str(e),
                    "filename": file.filename,
                    "timestamp": datetime.now().isoformat()
                }
            )
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid file format: {str(e)}"
            )
        except Exception as e:
            app_logger.error(f"File processing error: {str(e)}")
            # Broadcast error event
            await sse_manager.broadcast(
                event_type="generation_error",
                data={
                    "error": "File processing error",
                    "message": str(e),
                    "filename": file.filename,
                    "timestamp": datetime.now().isoformat()
                }
            )
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Error processing file: {str(e)}"
            )
        
        # Generate test cases using LLM orchestrator
        try:
            orchestrator = LLMOrchestratorService()
            response_data, model_used = await orchestrator.generate_test_cases(code_content)
            
            # Get test case count
            test_case_count = len(response_data.get("testCases", []))
            app_logger.info(f"Successfully generated {test_case_count} test cases")
            
            # Prepare response data (only count, not full test cases)
            response_obj = TestCaseGenerationResponse(
                testCaseCount=test_case_count,
                modelUsed=model_used,
                success=True
            )
            
            # Save test cases to file
            try:
                # Create full response data for saving
                save_data = {
                    "generatedAt": datetime.now().isoformat(),
                    "modelUsed": model_used,
                    "totalTestCases": len(response_data.get("testCases", [])),
                }

                # Also include flat testCases array
                save_data["testCases"] = response_data.get("testCases", [])
                
                # Generate filename from original file
                ext = '.py' if is_python else '.json'
                base_name = file.filename.replace(ext, '') if file.filename else 'testcases'
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                filename = f"{base_name}_generated_{timestamp}.json"
                
                saved_path = save_test_cases_to_file(
                    test_cases=save_data,
                    output_dir="output",
                    filename=filename
                )
                app_logger.info(f"Test cases saved to: {saved_path}")
                
                # Broadcast SSE event to all connected clients
                metrics = {
                    "test_cases": test_case_count,
                    "pages": 1,
                    "failed_pages": 0,
                    "page_count": 1,
                    "valid_locators": test_case_count * 2, # Approximation for loose files
                    "components": 1
                }
                
                await sse_manager.broadcast(
                    event_type="test_cases_updated",
                    data={
                        "testCaseCount": test_case_count,
                        "totalTestCases": len(response_data.get("testCases", [])),
                        "generatedAt": save_data.get("generatedAt"),
                        "modelUsed": model_used,
                        "filename": filename,
                        "metrics": metrics
                    }
                )
            except Exception as save_error:
                # Log error but don't fail the request
                app_logger.warning(f"Failed to save test cases to file: {str(save_error)}")
            
            return response_obj
            
        except Exception as e:
            app_logger.error(f"LLM generation error: {str(e)}")
            # Broadcast error event
            await sse_manager.broadcast(
                event_type="generation_error",
                data={
                    "error": "LLM generation failed",
                    "message": str(e),
                    "filename": file.filename if file else "unknown",
                    "timestamp": datetime.now().isoformat()
                }
            )
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Error generating test cases: {str(e)}"
            )
            
    except HTTPException:
        raise
    except Exception as e:
        app_logger.error(f"Unexpected error in generate_test_cases: {str(e)}")
        # Broadcast error event for unexpected errors
        try:
            await sse_manager.broadcast(
                event_type="generation_error",
                data={
                    "error": "Unexpected error",
                    "message": str(e),
                    "filename": file.filename if file else "unknown",
                    "timestamp": datetime.now().isoformat()
                }
            )
        except Exception as broadcast_error:
            app_logger.warning(f"Failed to broadcast error event: {str(broadcast_error)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Internal server error: {str(e)}"
        )


@router.get(
    "/testcases/count",
    response_model=TestCaseCount,
    status_code=status.HTTP_200_OK,
    summary="Get test cases count",
    description="Returns the number of test cases generated in the most recent run."
)
async def get_test_cases_count():
    """
    Get count of test cases from the latest generation.
    
    Returns:
        TestCaseCount with only the test case count number.
    """
    try:
        app_logger.info("Received request for test cases count")
        statistics = get_latest_test_cases_count(output_dir="output")
        
        response_obj = TestCaseCount(
            testCaseCount=statistics["testCaseCount"]
        )
        
        app_logger.info(f"Returning test case count: {statistics['testCaseCount']}")
        return response_obj
        
    except Exception as e:
        app_logger.error(f"Error getting test cases count: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error retrieving count: {str(e)}"
        )


@router.get(
    "/testcases",
    status_code=status.HTTP_200_OK,
    summary="Get generated test cases",
    description="Returns the full list of test cases from the most recent generation, grouped by page names."
)
async def get_test_cases():
    """
    Get the full test cases from the latest generation.
    
    Returns:
        TestCasesResponse with complete test cases data including:
        - testCases: Full array of test cases
        - totalTestCases: Count of test cases
        - generatedAt: Generation timestamp
        - modelUsed: Model that generated them
        - filename: Source filename
    """
    try:
        app_logger.info("Received request for test cases")
        test_cases_data = get_latest_test_cases(output_dir="output")
        
        # Extract page data with page names as keys (excluding metadata)
        pages_dict = {}
        metadata_keys = {"testCases", "totalTestCases", "generatedAt", "modelUsed", "filename", "pages"}
        for key, value in test_cases_data.items():
            if key not in metadata_keys and isinstance(value, dict) and ("url" in value or "testCases" in value):
                pages_dict[key] = value
        
        # Build response with page names as keys
        response_dict = {
            "testCases": test_cases_data.get("testCases", []),
            "totalTestCases": test_cases_data.get("totalTestCases", 0),
            "generatedAt": test_cases_data.get("generatedAt"),
            "modelUsed": test_cases_data.get("modelUsed"),
            "filename": test_cases_data.get("filename")
        }
        
        # Also include pages array for backward compatibility if it exists
        if "pages" in test_cases_data:
            response_dict["pages"] = test_cases_data["pages"]
        
        app_logger.info(f"Returning {test_cases_data.get('totalTestCases', 0)} test cases")
        return JSONResponse(content=response_dict)
        
    except Exception as e:
        app_logger.error(f"Error getting test cases: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND if "not found" in str(e).lower() else status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error retrieving test cases: {str(e)}"
        )


@router.get(
    "/testcases/stream",
    summary="Server-Sent Events stream for test cases",
    description="Stream real-time updates when test cases are generated. Returns Server-Sent Events (SSE)."
)
async def stream_test_cases():
    """
    Server-Sent Events endpoint for real-time test case updates.
    
    Clients connect to this endpoint and receive updates whenever new test cases are generated.
    
    Returns:
        StreamingResponse with SSE format
    """
    async def event_generator():
        """Generate SSE events."""
        queue = await sse_manager.connect()
        
        try:
            # Send initial connection message
            yield f"data: {json.dumps({'type': 'connected', 'message': 'Connected to test cases stream'})}\n\n"
            
            # Keep connection alive and send messages
            while True:
                try:
                    # Wait for message with timeout to keep connection alive
                    message = await asyncio.wait_for(queue.get(), timeout=30.0)
                    yield f"data: {message}\n\n"
                except asyncio.TimeoutError:
                    # Send keepalive ping
                    yield ": keepalive\n\n"
                except Exception as e:
                    app_logger.error(f"Error in SSE stream: {str(e)}")
                    break
                    
        except asyncio.CancelledError:
            app_logger.info("SSE connection cancelled by client")
        finally:
            await sse_manager.disconnect(queue)
    
    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"  # Disable buffering for nginx
        }
        )


@router.get(
    "/testcases/convert-to-csv",
    summary="Convert latest JSON test cases to CSV",
    description="Converts the most recently generated JSON test cases file to CSV format.",
    response_class=FileResponse
)
async def convert_test_cases_to_csv():
    """
    Convert the latest JSON test cases file to CSV format.
    
    Returns:
        CSV file download
    """
    try:
        app_logger.info("Received request to convert latest JSON to CSV")
        
        csv_file_path = convert_latest_json_to_csv(output_dir="output")
        
        # Get absolute path
        abs_csv_path = os.path.abspath(csv_file_path)
        
        if not os.path.exists(abs_csv_path):
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"CSV file not found: {csv_file_path}"
            )
        
        # Return CSV file as download
        return FileResponse(
            path=abs_csv_path,
            media_type="text/csv",
            filename=os.path.basename(csv_file_path),
            headers={"Content-Disposition": f"attachment; filename={os.path.basename(csv_file_path)}"}
        )
        
    except HTTPException:
        raise
    except Exception as e:
        app_logger.error(f"Error converting to CSV: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error converting to CSV: {str(e)}"
        )


@router.get(
    "/jira/test-connection",
    response_model=JiraConnectionTestResponse,
    status_code=status.HTTP_200_OK,
    summary="Test Jira connection",
    description="Tests the Jira API connection and validates configuration. Use this to verify your Jira setup before creating issues."
)
async def test_jira_connection():
    """
    Test Jira API connection and configuration.
    
    Returns:
        JiraConnectionTestResponse with connection status and project information
    """
    try:
        app_logger.info("Received request to test Jira connection")
        
        # Initialize Jira client
        try:
            jira_client = JiraClient()
        except ValueError as e:
            app_logger.error(f"Jira configuration error: {str(e)}")
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Jira configuration error: {str(e)}. Please check your .env file."
            )
        
        # Test connection
        connection_info = await jira_client.test_connection()
        
        return JiraConnectionTestResponse(**connection_info)
        
    except HTTPException:
        raise
    except Exception as e:
        app_logger.error(f"Jira connection test failed: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Jira connection test failed: {str(e)}"
        )


@router.post(
    "/testcases/create-jira-issues",
    response_model=JiraIssuesResponse,
    status_code=status.HTTP_200_OK,
    summary="Create Jira Tasks from test cases",
    description="Creates Jira Tasks (or other issue types) for the latest generated test cases. Default issue type is 'Task'. Requires Jira configuration in .env file."
)
async def create_jira_issues_from_test_cases(
    issue_type: str = Query(default="Task", description="Type of Jira issue to create (e.g., Task, Bug, Story). Default is 'Task'."),
    test_case_ids: Optional[str] = Query(default=None, description="Comma-separated list of test case IDs to create issues for (e.g., TC001,TC002). If not provided, creates issues for all test cases.")
):
    """
    Create Jira issues (Tasks) from the latest generated test cases.
    
    Args:
        issue_type: Type of Jira issue to create (default: "Task")
        test_case_ids: Optional comma-separated list of specific test case IDs to create issues for
        
    Returns:
        JiraIssuesResponse with created and failed issues
    """
    try:
        app_logger.info("Received request to create Jira issues from test cases")
        
        # Get latest test cases
        test_cases_data = get_latest_test_cases(output_dir="output")
        all_test_cases = test_cases_data.get("testCases", [])
        
        if not all_test_cases:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="No test cases found. Please generate test cases first."
            )
        
        # Filter test cases if specific IDs are provided
        if test_case_ids:
            requested_ids = [tc_id.strip() for tc_id in test_case_ids.split(",") if tc_id.strip()]
            test_cases = [tc for tc in all_test_cases if tc.get("id") in requested_ids]
            
            if not test_cases:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail=f"No test cases found with the provided IDs: {test_case_ids}"
                )
            
            app_logger.info(f"Filtering to {len(test_cases)} test cases from {len(requested_ids)} requested IDs")
        else:
            test_cases = all_test_cases
            app_logger.info(f"Creating issues for all {len(test_cases)} test cases")
        
        # Initialize Jira client
        try:
            jira_client = JiraClient()
        except ValueError as e:
            app_logger.error(f"Jira configuration error: {str(e)}")
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Jira configuration error: {str(e)}. Please check your .env file."
            )
        
        # Create Jira issues
        result = await jira_client.create_multiple_test_case_issues(
            test_cases=test_cases,
            issue_type=issue_type
        )
        
        app_logger.info(
            f"Jira issue creation completed: {result['successCount']} successful, "
            f"{result['failureCount']} failed out of {result['total']} total"
        )
        
        return JiraIssuesResponse(**result)
        
    except HTTPException:
        raise
    except Exception as e:
        app_logger.error(f"Error creating Jira issues: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error creating Jira issues: {str(e)}"
        )


@router.get("/health", summary="Health check endpoint")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "service": "test-case-generator"}

