"""
Run All Tests and Triage Failures
Runs all Playwright tests in tests/ directory and sends failures to triage engine
"""
import subprocess
import json
import os
import requests
import re
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration
API_URL = os.getenv("TRIAGE_ENGINE_API_URL", "http://localhost:8003/api/triage")
LLM_MODEL = os.getenv("LLM_MODEL", "gemma:2b")
BERT_URL = os.getenv("BERT_SERVER_URL", "http://localhost:8001/predict")
REPORT_FILE = "playwright-report.json"


def run_tests():
    """Run all Playwright tests in tests/ directory"""
    print("=" * 80)
    print("Running All Playwright Tests")
    print("=" * 80)
    print()
    try:
        # Run ALL tests in tests/ directory with JSON reporter
        # Directing output to a temporary file is more reliable on Windows
        import tempfile
        temp_report = os.path.join(tempfile.gettempdir(), "pw_report.json")
        
        cmd = f'npx playwright test tests/ --reporter=json > "{temp_report}"'
        print(f"Executing: {cmd}")
        
        result = subprocess.run(
            ["powershell", "-Command", cmd],
            capture_output=True,
            text=True
        )
        
        print(f"Tests completed with exit code: {result.returncode}")
        
        # Read the report from the temp file with proper encoding handling
        if os.path.exists(temp_report) and os.path.getsize(temp_report) > 0:
            content = None
            for encoding in ['utf-8', 'utf-16', 'utf-16-le', 'cp1252']:
                try:
                    with open(temp_report, 'r', encoding=encoding) as f:
                        content = f.read()
                    print(f"[OK] Read report with {encoding} encoding")
                    break
                except UnicodeDecodeError:
                    continue
            
            if content:
                with open(REPORT_FILE, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f"[OK] Report saved to {REPORT_FILE}")
                return True
            else:
                print("[ERROR] Failed to decode report file with any supported encoding")
                return False
        else:
            if result.stderr:
                print(f"[ERROR] Playwright stderr: {result.stderr}")
            print("[ERROR] No report generated by Playwright")
            return False
            
    except Exception as e:
        print(f"[ERROR] Error running tests: {e}")
        return False

def strip_ansi_codes(text):
    """Remove ANSI escape codes (color codes) from text"""
    if not text:
        return text
    # Pattern to match ANSI escape sequences
    ansi_escape = re.compile(r'\x1b\[[0-9;]*m')
    return ansi_escape.sub('', text)

def parse_failures():
    """Parse failures from the JSON report"""
    print("\n" + "=" * 80)
    print("Parsing Test Failures")
    print("=" * 80)
    print()
    
    if not os.path.exists(REPORT_FILE):
        print(f"[ERROR] Report file not found: {REPORT_FILE}")
        return []
    
    try:
        with open(REPORT_FILE, 'r', encoding='utf-8') as f:
            report = json.load(f)
        
        failures = []
        
        # Parse the Playwright report structure (handle nested suites)
        def process_suite(suite):
            # Process specs in this suite
            for spec in suite.get('specs', []):
                for test in spec.get('tests', []):
                    for result in test.get('results', []):
                        if result.get('status') in ['failed', 'timedOut']:
                            # Extract failure data
                            test_name = spec.get('title', 'Unknown Test')
                            file_path = os.path.basename(spec.get('file', 'unknown.spec.js'))
                            
                            error = result.get('error', {})
                            error_message = strip_ansi_codes(error.get('message', 'Test failed'))
                            stack_trace = strip_ansi_codes(error.get('stack', ''))
                            
                            # Build logs
                            logs = [
                                f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Test: {test_name}",
                                f"Status: {result.get('status')}",
                                f"Duration: {result.get('duration', 0)}ms",
                                f"Error: {error_message}"
                            ]
                            
                            failure = {
                                "test_name": test_name,
                                "file_path": file_path,
                                "error_message": error_message,
                                "stack_trace": stack_trace,
                                "logs": '\n'.join(logs),
                                "llm_model": LLM_MODEL,
                                "bert_url": BERT_URL,
                                "labels": ["playwright", "automated"],
                                "playwright_script_endpoint": f"http://localhost:8005/api/scripts/{file_path}"
                            }
                            
                            failures.append(failure)
            
            # Recursively process nested suites
            for nested_suite in suite.get('suites', []):
                process_suite(nested_suite)
        
        # Start processing from top-level suites
        for suite in report.get('suites', []):
            process_suite(suite)
        
        print(f"Found {len(failures)} failed test(s)")
        return failures
        
    except Exception as e:
        print(f"[ERROR] Error parsing report: {e}")
        import traceback
        traceback.print_exc()
        return []

def send_to_triage(failures):
    """Send failures to the triage engine"""
    print("\n" + "=" * 80)
    print("Sending Failures to Triage Engine")
    print("=" * 80)
    print()
    
    if not failures:
        print("No failures to send")
        return
    
    success = 0
    failed = 0
    
    for i, failure in enumerate(failures, 1):
        print(f"[{i}/{len(failures)}] {failure['test_name']}")
        print("-" * 80)
        
        try:
            response = requests.post(API_URL, json=failure, timeout=600)
            response.raise_for_status()
            result = response.json()
            
            print(f"[OK] SUCCESS")
            print(f"  Title: {result.get('title', 'N/A')}")
            print(f"  Error Line: {result.get('error_line', 'N/A')}")
            print(f"  Playwright Script: {result.get('playwright_script', 'N/A')}")
            print(f"  Triage Label: {result.get('triage_label', 'N/A')}")
            print(f"  ID: {result.get('id', 'N/A')}")
            success += 1
            
        except requests.exceptions.ConnectionError:
            print(f"[ERROR] ERROR: Cannot connect to {API_URL}")
            print("  Make sure the triage engine is running: python main.py")
            failed += 1
            
        except Exception as e:
            print(f"[ERROR] ERROR: {e}")
            failed += 1
        
        print()
    
    print("=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"[OK] Successfully triaged: {success}")
    print(f"[ERROR] Failed to triage: {failed}")
    print(f"Total failures: {len(failures)}")
    print()

def process_cicd_json(json_file_path):
    """Process CI/CD failure JSON without running tests"""
    print("\n" + "=" * 80)
    print("PROCESSING CI/CD FAILURE JSON")
    print("=" * 80)
    print()
    
    # Copy CI/CD JSON to playwright-report.json
    import shutil
    shutil.copy(json_file_path, REPORT_FILE)
    print(f"[OK] Copied {json_file_path} to {REPORT_FILE}")
    
    # Parse and triage
    failures = parse_failures()
    if failures:
        send_to_triage(failures)
    else:
        print("No failures found in CI/CD JSON")

def main():
    """Main workflow"""
    import sys
    
    # Check if CI/CD JSON file provided
    if len(sys.argv) > 1:
        json_file = sys.argv[1]
        if os.path.exists(json_file):
            process_cicd_json(json_file)
            return
        else:
            print(f"[ERROR] File not found: {json_file}")
            return
    
    print("\n" + "=" * 80)
    print("RUN ALL TESTS AND TRIAGE")
    print("=" * 80)
    print()
    
    # Step 1: Run tests
    if not run_tests():
        print("\n[ERROR] Failed to run tests")
        print("\nTry running manually:")
        print("  npx playwright test tests/")
        return
    
    # Step 2: Parse failures
    failures = parse_failures()
    
    if not failures:
        print("\n[OK] No failures found (all tests passed)")
        return
    
    # Step 3: Send to triage engine
    send_to_triage(failures)
    
    # Step 4: Next steps
    print("=" * 80)
    print("NEXT STEPS")
    print("=" * 80)
    print("View results with:")
    print("  python view_results.py")
    print("=" * 80)

if __name__ == "__main__":
    main()
