# Page_1_Cdbd Page Locators
class Page1CdbdLocators:
    FORMCOMPONENTS = "#navbarNavDropdown"
    FORMYFORMCOMPONENTS = "nav.navbar.navbar-expand-lg.bg-light"
    FORMYFORMCOMPONENTS_WELCOME = "html"
    FORMYFORMCOMPONENTS_WELCOME_1 = "body"
    HEADING_WELCOME_TO_FORMY = "h1"
    LINK_AUTOCOMPLETE = "a.btn.btn-lg"
    LINK_BUTTONS = "a.btn.btn-lg"
    LINK_CHECKBOX = "a.btn.btn-lg"
    LINK_COMPLETE_WEB_FORM = "a.btn.btn-lg"
    LINK_COMPONENTS = "#navbarDropdownMenuLink"
    LINK_DATEPICKER = "a.btn.btn-lg"
    LINK_DRAG_AND_DROP = "a.btn.btn-lg"
    LINK_DROPDOWN = "a.btn.btn-lg"
    LINK_ENABLED_AND_DISABLED_ELEMENTS = "a.btn.btn-lg"
    LINK_FILE_UPLOAD = "a.btn.btn-lg"
    LINK_FORM = "a.nav-link"
    LINK_FORMY = "#logo"
    LINK_KEY_AND_MOUSE_PRESS = "a.btn.btn-lg"
    LINK_MODAL = "a.btn.btn-lg"
    LINK_PAGE_SCROLL = "a.btn.btn-lg"
    LINK_RADIO_BUTTON = "a.btn.btn-lg"
    LINK_SWITCH_WINDOW = "a.btn.btn-lg"
