# Page_6_7142 Page Locators
class Page67142Locators:
    HEADING_DATEPICKER_64_111 = "h1"
    LINK_AUTOCOMPLETE = "xpath=//a[contains(text(), "
    LINK_BUTTONS = "xpath=//a[contains(text(), "
    LINK_CHECKBOX = "xpath=//a[contains(text(), "
    LINK_COMPLETE_WEB_FORM = "xpath=//a[contains(text(), "
    LINK_COMPONENTS = "#navbarDropdownMenuLink"
    LINK_DATEPICKER = "xpath=//a[contains(text(), "
    LINK_DRAG_AND_DROP = "xpath=//a[contains(text(), "
    LINK_DROPDOWN = "xpath=//a[contains(text(), "
    LINK_ENABLED_AND_DISABLED_ELEMENTS = "xpath=//a[contains(text(), "
    LINK_FILE_UPLOAD = "xpath=//a[contains(text(), "
    LINK_FORM = "a.nav-link"
    LINK_FORMY = "#logo"
    LINK_KEY_AND_MOUSE_PRESS = "xpath=//a[contains(text(), "
    LINK_MODAL = "xpath=//a[contains(text(), "
    LINK_PAGE_SCROLL = "xpath=//a[contains(text(), "
    LINK_RADIO_BUTTON = "xpath=//a[contains(text(), "
    LINK_SWITCH_WINDOW = "xpath=//a[contains(text(), "
