# Consolidated_Locators_State_3_Ca37 Page Locators
class ConsolidatedLocatorsState3Ca37Locators:
    A_COURSE_TO_HELP_YOU = "page.locator('#preheader')"
    BUILD_YOUR_FIRST_SCRAPER_IN_MI = "page.locator('#subhero')"
    DATABASE = "page.locator('xpath=//*[@id=\"benefits\"]/div[1]/div[2]/div[2]/p[1]/strong[2]')"
    EXCEL_SPREADSHEET = "page.locator('xpath=//*[@id=\"benefits\"]/div[1]/div[2]/div[2]/p[1]/strong[1]')"
    FAQ = "page.locator('#nav-faq')"
    FROM_GRADUATE_STUDENTS_AND_SOF = "page.locator('xpath=//*[@id=\"story\"]/div[1]/div[2]/div[1]/p[5]/strong[1]')"
    HARTLEY_BRODY = "page.locator('#footer-content')"
    HEADING_ADVANCED_TOPICS_REAL_WORLD_CH = "page.locator('xpath=//*[@id=\"pages\"]/section[1]/div[1]/div[1]/div[1]/div[5]/h3[1]')"
    HEADING_COUNTRIES_OF_THE_WORLD_A_SIMP = "page.locator('xpath=//*[@id=\"pages\"]/section[1]/div[1]/div[1]/div[1]/div[1]/h3[1]')"
    HEADING_FOLLOW_ALONG_STEPBYSTEP = "page.locator('xpath=//*[@id=\"benefits\"]/div[1]/div[1]/div[1]/h3[1]')"
    HEADING_GET_ACCESS_TO = "page.locator('xpath=//*[@id=\"benefits\"]/div[1]/div[3]/div[1]/h3[1]')"
    HEADING_GET_LIFETIME_ACCESS = "page.locator('xpath=//*[@id=\"fine-print\"]/div[1]/div[1]/div[1]/h3[1]')"
    HEADING_HOCKEY_TEAMS_FORMS_SEARCHING = "page.locator('xpath=//*[@id=\"pages\"]/section[1]/div[1]/div[1]/div[1]/div[2]/h3[1]')"
    HEADING_NEED_HELP = "page.locator('xpath=//*[@id=\"fine-print\"]/div[1]/div[1]/div[2]/h3[1]')"
    HEADING_OSCAR_WINNING_FILMS_AJAX_AND = "page.locator('xpath=//*[@id=\"pages\"]/section[1]/div[1]/div[1]/div[1]/div[3]/h3[1]')"
    HEADING_SCRAPE_ANY_WEBSITE = "page.locator('#header')"
    HEADING_SCRAPE_THIS_SITE_77_390 = "page.locator('h1')"
    HEADING_THIS_COURSE_HAS_BEEN_YEARS_IN = "page.locator('h2.text-center')"
    HEADING_TURTLES_ALL_THE_WAY_DOWN_FRAM = "page.locator('xpath=//*[@id=\"pages\"]/section[1]/div[1]/div[1]/div[1]/div[4]/h3[1]')"
    HEADING_WEB_SCRAPING_SANDBOX = "page.locator('h1')"
    HEADING_YOULL_LEARN_HOW_TO_SCRAPE = "page.locator('xpath=//*[@id=\"benefits\"]/div[1]/div[2]/div[2]/h3[1]')"
    I_LOVED_THE_COURSE_AND_BELIEV = "page.locator('xpath=//*[@id=\"story\"]/div[1]/div[1]/div[2]/blockquote[1]')"
    LEARN_HOW_TO_BUILD_YOUR_OWN_WE = "page.locator('#postheader')"
    LEARN_MORE_ABOUT_THE_COURSE = "page.locator('#video')"
    LESSONS = "page.locator('#nav-lessons')"
    LESSONS_AND_VIDEOS_HARTLEY_B = "page.locator('#footer')"
    LEV_SELECTOR = "page.locator('xpath=//*[@id=\"testimonials\"]/div[1]/div[1]/div[4]/blockquote[1]/footer[1]')"
    LINK_ADVANCED_TOPICS_REAL_WORLD_CH_370_853 = "page.locator('xpath=//*[@id=\"pages\"]/section[1]/div[1]/div[1]/div[1]/div[5]/h3[1]/a[1]')"
    LINK_BEGIN_LESSONS = "page.locator('a.btn.btn-lg.btn-primary')"
    LINK_COUNTRIES_OF_THE_WORLD_A_SIMP_370_161 = "page.locator('xpath=//a[contains(text(), \"Countries of the World: A Simple Example\")]')"
    LINK_EXPLORE_SANDBOX = "page.locator('a.btn.btn-lg.btn-default')"
    LINK_FAQ_526_10 = "page.locator('a.nav-link').nth(0)"
    LINK_GET_STARTED_NOW = "page.locator('a.gumroad-button').nth(0)"
    LINK_GET_STARTED_NOW_441_2987 = "page.locator('a.gumroad-button').nth(0)"
    LINK_GET_STARTED_NOW_441_4235 = "page.locator('a.gumroad-button').nth(0)"
    LINK_HOCKEY_TEAMS_FORMS_SEARCHING_370_327 = "page.locator('xpath=//a[contains(text(), \"Hockey Teams: Forms, Searching and Pagination\")]')"
    LINK_LESSONS_404_10 = "page.locator('a.nav-link').nth(0)"
    LINK_LOGIN_1116_10 = "page.locator('xpath=//a[contains(text(), \"Login\")]')"
    LINK_OSCAR_WINNING_FILMS_AJAX_AND_370_492 = "page.locator('xpath=//a[contains(text(), \"Oscar Winning Films: AJAX and Javascript\")]')"
    LINK_SANDBOX_278_10 = "page.locator('xpath=//a[contains(text(), \"Sandbox\")]')"
    LINK_SCRAPE_THIS_SITE_92_10 = "page.locator('a.nav-link.hidden-sm.hidden-xs')"
    LINK_TURTLES_ALL_THE_WAY_DOWN_FRAM_370_658 = "page.locator('xpath=//a[contains(text(), \"Turtles All the Way Down: Frames & iFrames\")]')"
    LOGIN = "page.locator('#nav-login')"
    NICHOLAS_RENOTTE = "page.locator('xpath=//*[@id=\"story\"]/div[1]/div[1]/div[2]/blockquote[1]/footer[1]')"
    NOTHING_TO_LOSE = "page.locator('u')"
    PAUL_BLANK = "page.locator('xpath=//*[@id=\"testimonials\"]/div[1]/div[1]/div[2]/blockquote[1]/footer[1]')"
    PURCHASE_SECURELY_WITH_PAYPAL = "page.locator('xpath=//*[@id=\"hero\"]/div[1]/div[2]/div[1]/small[1]')"
    PURCHASE_SECURELY_WITH_PAYPAL_77_2981 = "page.locator('xpath=//*[@id=\"second-buy-now\"]/div[1]/div[1]/div[1]/small[1]')"
    PURCHASE_SECURELY_WITH_PAYPAL_77_4229 = "page.locator('xpath=//*[@id=\"final-buy-now\"]/div[1]/div[1]/div[1]/small[1]')"
    SANDBOX = "page.locator('#nav-sandbox')"
    SCRAPE_THIS_SITE = "page.locator('#nav-homepage')"
    SCRAPE_THIS_SITE_SANDBOX_LES = "page.locator('#site-nav')"
    SCRAPE_THIS_SITE_SANDBOX_LES_0_10 = "page.locator('body')"
    SCRAPE_THIS_SITE_SANDBOX_LES_2 = "page.locator('#site-nav')"
    SCRAPE_THIS_SITE_THE_WORLDS = "page.locator('xpath=//*[@id=\"story\"]/div[1]/div[2]/div[1]/p[7]/strong[1]')"
    SIMPLE_BUT_IMPORTANT_LESSONS_O = "page.locator('xpath=//*[@id=\"story\"]/div[1]/div[2]/div[1]/p[2]/strong[1]')"
    START_COLLECTING_THE_DATA_YOU = "page.locator('xpath=//*[@id=\"postheader\"]/strong[1]')"
    WEB_SCRAPING = "page.locator('strong')"
    YEARS_IN_THE_MAKING = "page.locator('em')"
