# Page_2_F871 Page Locators
class Page2F871Locators:
    01 = "xpath=//*[@id="
    10 = "xpath=//*[@id="
    24 = "xpath=//*[@id="
    59 = "xpath=//*[@id="
    DATE = "xpath=/html/body/div[1]/form[1]/div[1]/div[7]/strong[1]"
    FIRST_NAME = "xpath=/html/body/div[1]/form[1]/div[1]/div[1]/strong[1]"
    HEADING_COMPLETE_WEB_FORM_64_111 = "h1"
    HIGHEST_LEVEL_OF_EDUCATION = "xpath=/html/body/div[1]/form[1]/div[1]/div[4]/div[1]/strong[1]"
    INPUT_EL = "#radio-button-1"
    INPUT_EL_79_509 = "#radio-button-2"
    INPUT_EL_79_533 = "#radio-button-3"
    INPUT_EL_79_613 = "#checkbox-1"
    INPUT_EL_79_637 = "#checkbox-2"
    INPUT_EL_79_661 = "#checkbox-3"
    INPUT_EL_79_831 = "#datepicker"
    INPUT_FIRST_NAME_79_199 = "#first-name"
    INPUT_JOB_TITLE_79_387 = "#job-title"
    INPUT_LAST_NAME_79_293 = "#last-name"
    JOB_TITLE = "xpath=/html/body/div[1]/form[1]/div[1]/div[3]/strong[1]"
    LAST_NAME = "xpath=/html/body/div[1]/form[1]/div[1]/div[2]/strong[1]"
    LINK_AUTOCOMPLETE = "xpath=//a[contains(text(), "
    LINK_BUTTON = "a.btn.btn-lg.btn-primary"
    LINK_BUTTONS = "xpath=//a[contains(text(), "
    LINK_CHECKBOX = "xpath=//a[contains(text(), "
    LINK_COMPLETE_WEB_FORM = "xpath=//a[contains(text(), "
    LINK_COMPONENTS = "#navbarDropdownMenuLink"
    LINK_DATEPICKER = "xpath=//a[contains(text(), "
    LINK_DRAG_AND_DROP = "xpath=//a[contains(text(), "
    LINK_DROPDOWN = "xpath=//a[contains(text(), "
    LINK_ENABLED_AND_DISABLED_ELEMENTS = "xpath=//a[contains(text(), "
    LINK_FILE_UPLOAD = "xpath=//a[contains(text(), "
    LINK_FORM = "a.nav-link"
    LINK_FORMY = "#logo"
    LINK_KEY_AND_MOUSE_PRESS = "xpath=//a[contains(text(), "
    LINK_MODAL = "xpath=//a[contains(text(), "
    LINK_PAGE_SCROLL = "xpath=//a[contains(text(), "
    LINK_RADIO_BUTTON = "xpath=//a[contains(text(), "
    LINK_SWITCH_WINDOW = "xpath=//a[contains(text(), "
    SELECT_AN_OPTION = "xpath=//*[@id="
    SEX = "xpath=/html/body/div[1]/form[1]/div[1]/div[5]/div[1]/strong[1]"
    YEARS_OF_EXPERIENCE = "xpath=/html/body/div[1]/form[1]/div[1]/div[6]/strong[1]"
    YEARS_OF_EXPERIENCE_79_737 = "#select-menu"
