# Page_3_9Ddb Page Locators
class Page39ddbLocators:
    ADDRESS = "xpath=/html/body/div[1]/form[1]/div[1]/div[1]/strong[1]"
    CITY = "xpath=/html/body/div[1]/form[1]/div[1]/div[4]/strong[1]"
    COUNTRY = "xpath=/html/body/div[1]/form[1]/div[1]/div[7]/strong[1]"
    HEADING_AUTOCOMPLETE_64_111 = "h1"
    INPUT_ADDRESS_79_199 = "#autocomplete"
    INPUT_EL = "#street_number"
    INPUT_EL_79_339 = "#route"
    INPUT_EL_79_409 = "#locality"
    INPUT_EL_79_479 = "#administrative_area_level_1"
    INPUT_EL_79_549 = "#postal_code"
    INPUT_EL_79_619 = "#country"
    LINK_AUTOCOMPLETE = "xpath=//a[contains(text(), "
    LINK_BUTTONS = "xpath=//a[contains(text(), "
    LINK_CHECKBOX = "xpath=//a[contains(text(), "
    LINK_COMPLETE_WEB_FORM = "xpath=//a[contains(text(), "
    LINK_COMPONENTS = "#navbarDropdownMenuLink"
    LINK_DATEPICKER = "xpath=//a[contains(text(), "
    LINK_DRAG_AND_DROP = "xpath=//a[contains(text(), "
    LINK_DROPDOWN = "xpath=//a[contains(text(), "
    LINK_ENABLED_AND_DISABLED_ELEMENTS = "xpath=//a[contains(text(), "
    LINK_FILE_UPLOAD = "xpath=//a[contains(text(), "
    LINK_FORM = "a.nav-link"
    LINK_FORMY = "#logo"
    LINK_KEY_AND_MOUSE_PRESS = "xpath=//a[contains(text(), "
    LINK_MODAL = "xpath=//a[contains(text(), "
    LINK_PAGE_SCROLL = "xpath=//a[contains(text(), "
    LINK_RADIO_BUTTON = "xpath=//a[contains(text(), "
    LINK_SWITCH_WINDOW = "xpath=//a[contains(text(), "
    STATE = "xpath=/html/body/div[1]/form[1]/div[1]/div[5]/strong[1]"
    STREET_ADDRESS = "xpath=/html/body/div[1]/form[1]/div[1]/div[2]/strong[1]"
    STREET_ADDRESS_2 = "xpath=/html/body/div[1]/form[1]/div[1]/div[3]/strong[1]"
    ZIP_CODE = "xpath=/html/body/div[1]/form[1]/div[1]/div[6]/strong[1]"
