# Page URLs for Playwright tests
BASE_URL = "https://example.com/"

PAGE_10_BE84_URL = "https://example.com/"
PAGE_11_URL = "http://www.scrapethissite.com/robots.txt"
PAGE_12_URL = "http://www.scrapethissite.com/pages/forms/?page_num=1"
PAGE_13_URL = "http://www.scrapethissite.com/pages/forms/?page_num=2"
PAGE_14_URL = "http://www.scrapethissite.com/pages/forms/?page_num=3"
PAGE_15_URL = "http://www.scrapethissite.com/pages/forms/?page_num=4"
PAGE_16_URL = "http://www.scrapethissite.com/pages/forms/?page_num=5"
PAGE_17_URL = "http://www.scrapethissite.com/pages/forms/?page_num=6"
PAGE_18_URL = "http://www.scrapethissite.com/pages/forms/?page_num=7"
PAGE_19_URL = "http://www.scrapethissite.com/pages/forms/?page_num=8"
PAGE_1_CDBD_URL = "https://example.com/"
PAGE_20_URL = "http://www.scrapethissite.com/pages/forms/?page_num=9"
PAGE_21_URL = "http://www.scrapethissite.com/pages/forms/?page_num=10"
PAGE_22_URL = "http://www.scrapethissite.com/pages/forms/?page_num=11"
PAGE_23_URL = "http://www.scrapethissite.com/pages/forms/?page_num=12"
PAGE_2_F871_URL = "https://example.com/"
PAGE_3_9DDB_URL = "https://example.com/"
PAGE_4_2B0A_URL = "https://example.com/"
PAGE_5_AA33_URL = "https://example.com/"
PAGE_6_7142_URL = "https://example.com/"
PAGE_7_181A_URL = "https://example.com/"
PAGE_8_2F35_URL = "https://example.com/"
PAGE_9_E3BD_URL = "https://example.com/"
CONSOLIDATED_LOCATORS_STATE_2_1DB2_URL = " "
LOGIN_URL = ""
SIGNUP_URL = ""
WELCOME_URL = ""
CONSOLIDATED_LOCATORS_STATE_1_1F0D_URL = "https://example.com/"
CONSOLIDATED_LOCATORS_STATE_3_CA37_URL = "https://example.com/"
CONSOLIDATED_STATE_1_1F0D_URL = "https://example.com/"
CONSOLIDATED_STATE_2_1DB2_URL = "https://example.com/"
CONSOLIDATED_STATE_3_CA37_URL = "https://example.com/"
CONSOLIDATED_STATE_4_E555_URL = "https://example.com/"